
#pragma once

#include <core/mirror.h>
#include <geometry/shape_poly_set.h>
#include <geometry/approximation.h>
#include <properties/property.h>
#include <stroke_params.h>
#include <trigo.h>
#include <api/serializable.h>

class LINE_READER;
class EDA_DRAW_FRAME;
class FOOTPRINT;
class MSG_PANEL_ITEM;

using KIGFX::COLOR4D;

enum class SHAPE_T : int
{
    UNDEFINED = -1,
    SEGMENT = 0,
    RECTANGLE,      ///< Use RECTANGLE instead of RECT to avoid collision in a Windows header.
    ARC,
    CIRCLE,
    POLY,
    BEZIER
};


// WARNING: Do not change these values without updating dialogs that depend on their position values
enum class FILL_T : int
{
    NO_FILL = 1,
    FILLED_SHAPE,               ///< Fill with object color.
    FILLED_WITH_BG_BODYCOLOR,   //< Fill with background body color.
    FILLED_WITH_COLOR           //< Fill with a separate color.
};


/// Holding struct to keep originating midpoint
struct ARC_MID
{
    VECTOR2I mid;
    VECTOR2I start;
    VECTOR2I end;
    VECTOR2I center;
};

class EDA_SHAPE : public SERIALIZABLE
{
public:
    EDA_SHAPE( SHAPE_T aType, int aLineWidth, FILL_T aFill );

    /// Construct an EDA_SHAPE from an abstract SHAPE geometry.
    EDA_SHAPE( const SHAPE& aShape );

    // Do not create a copy constructor & operator=.
    // The ones generated by the compiler are adequate.

    virtual ~EDA_SHAPE();

    void SwapShape( EDA_SHAPE* aImage );

    //void Serialize( google::protobuf::Any &aContainer ) const override;
    //bool Deserialize( const google::protobuf::Any &aContainer ) override;

    QString ShowShape() const;

    QString SHAPE_T_asString() const;

    virtual bool IsProxyItem() const { return m_proxyItem; }
    virtual void SetIsProxyItem( bool aIsProxy = true ) { m_proxyItem = aIsProxy; }

    bool IsFilled() const
    {
        return GetFillMode() != FILL_T::NO_FILL;
    }

    virtual bool IsFilledForHitTesting() const
    {
        return IsFilled();
    }

    virtual void SetFilled( bool aFlag )
    {
        setFilled( aFlag );
    }

    void SetFillMode( FILL_T aFill )           { m_fill = aFill; }
    FILL_T GetFillMode() const                 { return m_fill; }

    bool IsClosed() const;

    COLOR4D GetFillColor() const               { return m_fillColor; }
    void SetFillColor( const COLOR4D& aColor ) { m_fillColor = aColor; }

    void SetWidth( int aWidth )                { m_stroke.SetWidth( aWidth ); }
    virtual int GetWidth() const               { return m_stroke.GetWidth(); }
    virtual int GetEffectiveWidth() const      { return GetWidth(); }

    void       SetLineStyle( const LINE_STYLE aStyle );
    LINE_STYLE GetLineStyle() const;

    void    SetLineColor( const COLOR4D& aColor ) { m_stroke.SetColor( aColor ); }
    COLOR4D GetLineColor() const                  { return m_stroke.GetColor(); }

    void SetShape( SHAPE_T aShape )            { m_shape = aShape; }
    SHAPE_T GetShape() const                   { return m_shape; }

    const VECTOR2I& GetStart() const { return m_start; }
    int             GetStartY() const { return m_start.y; }
    int             GetStartX() const { return m_start.x; }

    void SetStart( const VECTOR2I& aStart )
    {
        m_start = aStart;
        m_endsSwapped = false;
    }

    void SetStartY( int y )
    {
        m_start.y = y;
        m_endsSwapped = false;
    }

    void SetStartX( int x )
    {
        m_start.x = x;
        m_endsSwapped = false;
    }

    void SetCenterY( int y )
    {
        m_end.y += y - m_start.y;
        m_start.y = y;
    }

    void SetCenterX( int x )
    {
        m_end.x += x - m_start.x;
        m_start.x = x;
    }

    const VECTOR2I& GetEnd() const { return m_end; }
    int             GetEndY() const { return m_end.y; }
    int             GetEndX() const { return m_end.x; }

    void SetEnd( const VECTOR2I& aEnd )
    {
        m_end = aEnd;
        m_endsSwapped = false;
    }

    void SetEndY( int aY )
    {
        m_end.y = aY;
        m_endsSwapped = false;
    }

    void SetEndX( int aX )
    {
        m_end.x = aX;
        m_endsSwapped = false;
    }

    void SetRadius( int aX )
    {
        m_end = m_start + VECTOR2I( aX, 0 );
    }

    virtual VECTOR2I GetTopLeft() const { return GetStart(); }
    virtual VECTOR2I GetBotRight() const { return GetEnd(); }

    virtual void SetTop( int val ) { SetStartY( val ); }
    virtual void SetLeft( int val ) { SetStartX( val ); }
    virtual void SetRight( int val ) { SetEndX( val ); }
    virtual void SetBottom( int val ) { SetEndY( val ); }

    void            SetBezierC1( const VECTOR2I& aPt ) { m_bezierC1 = aPt; }
    const VECTOR2I& GetBezierC1() const { return m_bezierC1; }

    void            SetBezierC2( const VECTOR2I& aPt ) { m_bezierC2 = aPt; }
    const VECTOR2I& GetBezierC2() const { return m_bezierC2; }

    VECTOR2I getCenter() const;
    void     SetCenter( const VECTOR2I& aCenter );

    void SetArcAngleAndEnd( const EDA_ANGLE& aAngle, bool aCheckNegativeAngle = false );

    EDA_ANGLE GetArcAngle() const;

    EDA_ANGLE GetSegmentAngle() const;

    bool EndsSwapped() const { return m_endsSwapped; }

    // Some attributes are read only, since they are derived from m_Start, m_End, and m_Angle.
    // No Set...() function for these attributes.

    VECTOR2I              GetArcMid() const;
    std::vector<VECTOR2I> GetRectCorners() const;
    std::vector<VECTOR2I> GetCornersInSequence( EDA_ANGLE angle ) const;

    void CalcArcAngles( EDA_ANGLE& aStartAngle, EDA_ANGLE& aEndAngle ) const;

    int GetRadius() const;

    void SetArcGeometry( const VECTOR2I& aStart, const VECTOR2I& aMid, const VECTOR2I& aEnd );

    void SetCachedArcData( const VECTOR2I& aStart, const VECTOR2I& aMid, const VECTOR2I& aEnd,
                           const VECTOR2I& aCenter );

    const std::vector<VECTOR2I>& GetBezierPoints() const { return m_bezierPoints; }

    void DupPolyPointsList( std::vector<VECTOR2I>& aBuffer ) const;

    int GetPointCount() const;

    // Accessors to the polygonal shape
    SHAPE_POLY_SET& GetPolyShape() { return m_poly; }
    const SHAPE_POLY_SET& GetPolyShape() const { return m_poly; }

    bool IsPolyShapeValid() const;

    void SetPolyShape( const SHAPE_POLY_SET& aShape )
    {
        m_poly = aShape;

        for( int ii = 0; ii < m_poly.OutlineCount(); ++ii )
        {
            if( m_poly.HoleCount( ii ) )
            {
                m_poly.Fracture();
                break;
            }
        }
    }

    void SetPolyPoints( const std::vector<VECTOR2I>& aPoints );

    void RebuildBezierToSegmentsPointsList( int aMaxError );

    virtual std::vector<SHAPE*> MakeEffectiveShapes( bool aEdgeOnly = false ) const
    {
        return makeEffectiveShapes( aEdgeOnly );
    }

    void ShapeGetMsgPanelInfo( EDA_DRAW_FRAME* aFrame, std::vector<MSG_PANEL_ITEM>& aList );

    void SetLength( const double& aLength );

    void SetRectangleHeight( const int& aHeight );

    void SetRectangleWidth( const int& aWidth );

    void SetRectangle( const long long int& aHeight, const long long int& aWidth );

    void SetSegmentAngle( const EDA_ANGLE& aAngle );

    bool IsClockwiseArc() const;

    double GetLength() const;

    int GetRectangleHeight() const;
    int GetRectangleWidth() const;

    void TransformShapeToPolygon( SHAPE_POLY_SET& aBuffer, int aClearance, int aError,
                                  ERROR_LOC aErrorLoc, bool ignoreLineWidth = false ) const;

    int Compare( const EDA_SHAPE* aOther ) const;

    double Similarity( const EDA_SHAPE& aOther ) const;

    bool operator==( const EDA_SHAPE& aOther ) const;

protected:
    QString getFriendlyName() const;

    void     setPosition( const VECTOR2I& aPos );
    VECTOR2I getPosition() const;

    virtual void setFilled( bool aFlag )
    {
        m_fill = aFlag ? FILL_T::FILLED_SHAPE : FILL_T::NO_FILL;
    }

    void move( const VECTOR2I& aMoveVector );
    void rotate( const VECTOR2I& aRotCentre, const EDA_ANGLE& aAngle );
    void flip( const VECTOR2I& aCentre, FLIP_DIRECTION aFlipDirection );
    void scale( double aScale );

    virtual EDA_ANGLE getDrawRotation() const { return ANGLE_0; }

    const BOX2I getBoundingBox() const;

    void computeArcBBox( BOX2I& aBBox ) const;

    bool hitTest( const VECTOR2I& aPosition, int aAccuracy = 0 ) const;
    bool hitTest( const BOX2I& aRect, bool aContained, int aAccuracy = 0 ) const;

    const std::vector<VECTOR2I> buildBezierToSegmentsPointsList( int aMaxError ) const;

    void beginEdit( const VECTOR2I& aStartPoint );
    bool continueEdit( const VECTOR2I& aPosition );
    void calcEdit( const VECTOR2I& aPosition );

    void endEdit( bool aClosed = true );
    void setEditState( int aState ) { m_editState = aState; }

    std::vector<SHAPE*> makeEffectiveShapes( bool aEdgeOnly, bool aLineChainOnly = false ) const;

    virtual int getMaxError() const { return 100; }

protected:
    bool                  m_endsSwapped;  // true if start/end were swapped e.g. SetArcAngleAndEnd
    SHAPE_T               m_shape;        // Shape: line, Circle, Arc
    STROKE_PARAMS         m_stroke;       // Line style, width, etc.
    FILL_T                m_fill;
    COLOR4D               m_fillColor;

    long long int         m_rectangleHeight;
    long long int         m_rectangleWidth;

    double                m_segmentLength;
    EDA_ANGLE             m_segmentAngle;

    VECTOR2I              m_start;             // Line start point or Circle center
    VECTOR2I              m_end;               // Line end point or Circle 3 o'clock point

    VECTOR2I              m_arcCenter;         // Used only for Arcs: arc end point
    ARC_MID               m_arcMidData;        // Used to store originating data

    VECTOR2I              m_bezierC1;          // Bezier Control Point 1
    VECTOR2I              m_bezierC2;          // Bezier Control Point 2

    std::vector<VECTOR2I> m_bezierPoints;
    SHAPE_POLY_SET        m_poly;              // Stores the S_POLYGON shape

    int                   m_editState;
    bool                  m_proxyItem;         // A shape storing proxy information (ie: a pad
                                               //   number box, thermal spoke template, etc.)
};

