
#ifndef SCH_SHAPE_H
#define SCH_SHAPE_H

#include <sch_item.h>
#include <eda_shape.h>
#include <schematic.h>


class SCH_SHAPE : public SCH_ITEM, public EDA_SHAPE
{
public:
    SCH_SHAPE( SHAPE_T aShape = SHAPE_T::UNDEFINED, SCH_LAYER_ID aLayer = LAYER_NOTES,
               int aLineWidth = 0, FILL_T aFillType = FILL_T::NO_FILL,
               KICAD_T aType = SCH_SHAPE_T );

    // Do not create a copy constructor.  The one generated by the compiler is adequate.

    virtual ~SCH_SHAPE() override {}

    QString GetClass() const override
    {
        return "SCH_SHAPE";
    }

    void SwapData( SCH_ITEM* aItem ) override;

    bool HitTest( const VECTOR2I& aPosition, int aAccuracy = 0 ) const override;
    bool HitTest( const BOX2I& aRect, bool aContained, int aAccuracy = 0 ) const override;

    bool IsEndPoint( const VECTOR2I& aPoint ) const override;

    int GetPenWidth() const override                  { return GetStroke().GetWidth(); }

    bool HasLineStroke() const override               { return true; }
    STROKE_PARAMS GetStroke() const override          { return m_stroke; }
    void SetStroke( const STROKE_PARAMS& aStroke ) override;

    int GetEffectiveWidth() const override;

    LINE_STYLE GetEffectiveLineStyle() const
    {
        if( m_stroke.GetLineStyle() == LINE_STYLE::DEFAULT )
            return LINE_STYLE::SOLID;
        else
            return m_stroke.GetLineStyle();
    }

    void SetFilled( bool aFilled ) override;

    const BOX2I GetBoundingBox() const override;

    VECTOR2I GetPosition() const override                   { return getPosition(); }
    void     SetPosition( const VECTOR2I& aPos ) override   { setPosition( aPos ); }

    VECTOR2I GetCenter() const { return getCenter(); }

    void BeginEdit( const VECTOR2I& aStartPoint ) override  { beginEdit( aStartPoint ); }
    bool ContinueEdit( const VECTOR2I& aPosition ) override { return continueEdit( aPosition ); }
    void CalcEdit( const VECTOR2I& aPosition ) override     { calcEdit( aPosition ); }
    void EndEdit( bool aClosed = false ) override           { endEdit(); }
    void SetEditState( int aState )                         { setEditState( aState ); }

    void Move( const VECTOR2I& aOffset ) override;

    void Normalize();

    void MirrorHorizontally( int aCenter ) override;
    void MirrorVertically( int aCenter ) override;
    void Rotate( const VECTOR2I& aCenter, bool aRotateCCW ) override;

    void AddPoint( const VECTOR2I& aPosition );

    /**
    * Make a set of SHAPE objects representing the SCH_SHAPE.  Caller owns the objects.
    *
    * @param aEdgeOnly indicates only edges should be generated (even if 0 width), and no fill
    *                  shapes.
    */
    std::vector<SHAPE*> MakeEffectiveShapes( bool aEdgeOnly = false ) const override
    {
        return makeEffectiveShapes( aEdgeOnly, true );
    }

    void Print( const SCH_RENDER_SETTINGS* aSettings, int aUnit, int aBodyStyle,
                const VECTOR2I& aOffset, bool aForceNoFill, bool aDimmed ) override;

    void PrintBackground( const SCH_RENDER_SETTINGS* aSettings, int aUnit, int aBodyStyle,
                          const VECTOR2I& aOffset, bool aDimmed ) override;

    void Plot( PLOTTER* aPlotter, bool aBackground, const SCH_PLOT_OPTS& aPlotOpts,
               int aUnit, int aBodyStyle, const VECTOR2I& aOffset, bool aDimmed ) override;

    void GetMsgPanelInfo( EDA_DRAW_FRAME* aFrame, std::vector<MSG_PANEL_ITEM>& aList ) override;

    QString GetItemDescription( UNITS_PROVIDER* aUnitsProvider, bool aFull ) const override;

    BITMAPS GetMenuImage() const override;

    EDA_ITEM* Clone() const override;

    std::vector<int> ViewGetLayers() const override;

    double Similarity( const SCH_ITEM& aOther ) const override;

    bool operator==( const SCH_ITEM& aOther ) const override;

#if defined(DEBUG)
    void Show( int nestLevel, std::ostream& os ) const override { ShowDummy( os ); }
#endif

protected:
    void setFilled( bool aFlag ) override
    {
        m_fill = aFlag ? FILL_T::FILLED_WITH_COLOR : FILL_T::NO_FILL;
    }

    int getMaxError() const override
    {
        if( SCHEMATIC* schematic = Schematic() )
            return schematic->Settings().m_MaxError;
        else
            return schIUScale.mmToIU( ARC_LOW_DEF_MM );
    }

    /**
     * @copydoc SCH_ITEM::compare()
     *
     * The circle specific sort order is as follows:
     *      - Circle horizontal (X) position.
     *      - Circle vertical (Y) position.
     *      - Circle radius.
     */
    int compare( const SCH_ITEM& aOther, int aCompareFlags = 0 ) const override;
};


#endif    // SCH_SHAPE_H
