
// QT_TRANSFORMATION_COMPLETED - Verified on 2025-09-05
#ifndef PCB_TEXT_H
#define PCB_TEXT_H

#include <eda_text.h>
#include <board_item.h>


class LINE_READER;
class MSG_PANEL_ITEM;
class FOOTPRINT;


class PCB_TEXT : public BOARD_ITEM, public EDA_TEXT
{
public:
    PCB_TEXT( BOARD_ITEM* parent, KICAD_T idtype = PCB_TEXT_T );

    PCB_TEXT( FOOTPRINT* aParent, KICAD_T idtype = PCB_TEXT_T );

    // Do not create a copy constructor & operator=.
    // The ones generated by the compiler are adequate.

    ~PCB_TEXT();

    void CopyFrom( const BOARD_ITEM* aOther ) override;

    static inline bool ClassOf( const EDA_ITEM* aItem )
    {
        return aItem && PCB_TEXT_T == aItem->Type();
    }

    bool IsType( const std::vector<KICAD_T>& aScanTypes ) const override
    {
        if( BOARD_ITEM::IsType( aScanTypes ) )
            return true;

        for( KICAD_T scanType : aScanTypes )
        {
            if( scanType == PCB_LOCATE_TEXT_T )
                return true;
        }

        return false;
    }

    //void Serialize( google::protobuf::Any &aContainer ) const override;
    //bool Deserialize( const google::protobuf::Any &aContainer ) override;

    void StyleFromSettings( const BOARD_DESIGN_SETTINGS& settings ) override;

    /**
     * Called when rotating the parent footprint.
     */
    void KeepUpright();

    QString GetShownText( bool aAllowExtraText, int aDepth = 0 ) const override;

    bool Matches( const EDA_SEARCH_DATA& aSearchData, void* aAuxData ) const override;

    virtual VECTOR2I GetPosition() const override
    {
        return EDA_TEXT::GetTextPos();
    }

    virtual void SetPosition( const VECTOR2I& aPos ) override
    {
        EDA_TEXT::SetTextPos( aPos );
    }

    void Move( const VECTOR2I& aMoveVector ) override
    {
        EDA_TEXT::Offset( aMoveVector );
    }

    void Rotate( const VECTOR2I& aRotCentre, const EDA_ANGLE& aAngle ) override;

    void Mirror( const VECTOR2I& aCentre, FLIP_DIRECTION aFlipDirection ) override;

    void Flip( const VECTOR2I& aCentre, FLIP_DIRECTION aFlipDirection ) override;

    void GetMsgPanelInfo( EDA_DRAW_FRAME* aFrame, std::vector<MSG_PANEL_ITEM>& aList ) override;

    bool TextHitTest( const VECTOR2I& aPoint, int aAccuracy = 0 ) const override;
    bool TextHitTest( const BOX2I& aRect, bool aContains, int aAccuracy = 0 ) const override;

    bool HitTest( const VECTOR2I& aPosition, int aAccuracy ) const override
    {
        return TextHitTest( aPosition, aAccuracy );
    }

    bool HitTest( const BOX2I& aRect, bool aContained, int aAccuracy = 0 ) const override
    {
        return TextHitTest( aRect, aContained, aAccuracy );
    }

    QString GetClass() const override
    {
        return QStringLiteral( "PCB_TEXT" );
    }

    /**
     * Function TransformTextToPolySet
     * Convert the text to a polygonSet describing the actual character strokes (one per segment).
     * Circles and arcs are approximated by segments.
     * @param aBuffer SHAPE_POLY_SET to store the polygon corners
     * @param aClearance the clearance around the text
     * @param aMaxError the maximum error to allow when approximating curves
     */
    void TransformTextToPolySet( SHAPE_POLY_SET& aBuffer, int aClearance, int aMaxError,
                                 ERROR_LOC aErrorLoc ) const;

    void TransformShapeToPolygon( SHAPE_POLY_SET& aBuffer, PCB_LAYER_ID aLayer, int aClearance,
                                  int aMaxError, ERROR_LOC aErrorLoc,
                                  bool aIgnoreLineWidth = false ) const override;

    // @copydoc BOARD_ITEM::GetEffectiveShape
    virtual std::shared_ptr<SHAPE>
    GetEffectiveShape( PCB_LAYER_ID aLayer = UNDEFINED_LAYER,
                       FLASHING aFlash = FLASHING::DEFAULT ) const override;

    SHAPE_POLY_SET GetKnockoutCache( const KIFONT::FONT* aFont, const QString& forResolvedText,
                                     int aMaxError ) const;

    virtual QString GetTextTypeDescription() const;

    QString GetItemDescription( UNITS_PROVIDER* aUnitsProvider, bool aFull ) const override;

    BITMAPS GetMenuImage() const override;

    /**
     * @return the text rotation for drawings and plotting the footprint rotation is taken
     *         in account.
     */
    EDA_ANGLE GetDrawRotation() const override;

    const BOX2I ViewBBox() const override;

    std::vector<int> ViewGetLayers() const override;

    ///< @copydoc VIEW_ITEM::ViewGetLOD
    double ViewGetLOD( int aLayer, const KIGFX::VIEW* aView ) const override;

    // Virtual function
    const BOX2I GetBoundingBox() const override;

    EDA_ITEM* Clone() const override;

    double Similarity( const BOARD_ITEM& aBoardItem ) const override;

    bool operator==( const PCB_TEXT& aOther ) const;
    bool operator==( const BOARD_ITEM& aBoardItem ) const override;

#if defined(DEBUG)
    virtual void Show( int nestLevel, std::ostream& os ) const override { ShowDummy( os ); }
#endif

protected:
    /**
     * Build a nominally rectangular bounding box for the rendered text.  (It's not a BOX2I
     * because it will be a diamond shape for non-cardinally rotated text.)
     */
    void buildBoundingHull( SHAPE_POLY_SET* aBuffer, const SHAPE_POLY_SET& aRenderedText,
                            int aClearance ) const;

    virtual void swapData( BOARD_ITEM* aImage ) override;

    int getKnockoutMargin() const;

    const KIFONT::METRICS& getFontMetrics() const override { return GetFontMetrics(); }

private:
    mutable QString            m_knockout_cache_text;
    mutable TEXT_ATTRIBUTES     m_knockout_cache_text_attrs;
    mutable EDA_ANGLE           m_knockout_cache_angle;
    mutable VECTOR2I            m_knockout_cache_pos;
    mutable SHAPE_POLY_SET      m_knockout_cache;
};

#endif  // #define PCB_TEXT_H
