// Placeholder protobuf header for base_types.pb.h
// This is a minimal stub to allow compilation testing
// In a real build, this would be generated by protoc from base_types.proto

#pragma once

namespace kiapi {
namespace common {
namespace types {

// Minimal stub definitions to allow compilation
// Real protobuf messages would be generated here

}
}
}